# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20161016_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameFormatConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, unique=True)),
                ('default_to_username', models.BooleanField(default=True, help_text='If a user has no main_character, default to using their Auth username instead.')),
                ('format', models.CharField(help_text='For information on constructing name formats, please see the <a href="https://allianceauth.readthedocs.io/en/latest/features/nameformats">name format documentation</a>', max_length=100)),
                ('nontenant_format', models.CharField(blank=True, default='', help_text='Used if the user is not a member of one of the configured tenant corps or alliances. If one is not specified, the member format is used instead.', max_length=100)),
            ],
        ),
    ]
