# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 10:53
from __future__ import unicode_literals

from django.db import migrations, models
from django.core.exceptions import ObjectDoesNotExist
import django.db.models.deletion
import logging

logger = logging.getLogger(__name__)


def forward(apps, schema_editor):
    AuthServicesInfo = apps.get_model("authentication", "AuthServicesInfo")
    EveCharacter = apps.get_model("eveonline", "EveCharacter")

    for authinfo in AuthServicesInfo.objects.all():
        try:
            if authinfo.main_char_id:
                eve_char = EveCharacter.objects.get(character_id=authinfo.main_char_id)
                authinfo.main_character = eve_char
                authinfo.save()
        except ObjectDoesNotExist:
            logger.warn("Failed to migrate main_char_id for user {} - main_char_id {}".format(authinfo.user.username,
                                                                                              authinfo.main_char_id))


def reverse(apps, schema_editor):
    AuthServicesInfo = apps.get_model("authentication", "AuthServicesInfo")

    for authinfo in AuthServicesInfo.objects.all():
        try:
            if authinfo.main_character:
                authinfo.main_char_id = authinfo.main_character.character_id
                authinfo.save()
        except ObjectDoesNotExist:
            logger.warn("Failed to migrate main_char_id for user {} - main_character.character_id {}".format(
                authinfo.user.username, authinfo.main_character.character_id))


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0007_unique_id_name'),
        ('authentication', '0013_service_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='authservicesinfo',
            name='main_character',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eveonline.EveCharacter'),
        ),
        migrations.AlterField(
            model_name='authservicesinfo',
            name='state',
            field=models.CharField(blank=True, choices=[(None, 'None'), ('Blue', 'Blue'), ('Member', 'Member')], default=None, max_length=10, null=True),
        ),
        # Migrate data
        migrations.RunPython(forward, reverse),
        migrations.RemoveField(
            model_name='authservicesinfo',
            name='main_char_id',
        ),
    ]
